function help() {
  const d = $("editor");
  dialogTrigger = document.activeElement;
  d.classList.remove("appearance-dialog", "todo-import-dialog");
  d.innerHTML =
    '<div class="dialog-top"><div><h2 id="dialog-title">Cómo usar Compás, desde el principio</h2><p class="hint">Compás · Versión ' +
    e(VERSION) +
    " · En tu equipo</p></div>" +
    btn("Cerrar", "close", "", "ghost") +
    '</div><div class="dialog-body"><h3>1. Descarga y descomprime el ZIP</h3><p>Descarga <strong>Compas-para-tesistas.zip</strong> desde el repositorio de Compás. En Windows, haz clic derecho sobre el ZIP y elige <strong>Extraer todo</strong>. En Mac, haz doble clic sobre el ZIP. Busca la carpeta extraída <strong>Compas</strong> y guárdala en un lugar fijo de tu computadora. <strong>Esta versión se usa en computadora, con un navegador habitual; no tiene una versión de trabajo para celular o tableta.</strong></p>' +
    '<h3>2. Abre Compas.html: esa es la aplicación</h3><p>Dentro de la carpeta extraída, abre primero <strong>Empezar-aqui.html</strong> si quieres leer las instrucciones. Para trabajar, haz doble clic en <strong>Compas.html</strong>. Se abre en tu navegador; <strong>no hay que instalar nada</strong>. Si aparece un editor de texto, usa «Abrir con» y elige tu navegador habitual. Abre el archivo de la carpeta extraída, no el que está dentro del ZIP.</p><p class="hint">Materiales-en-linea.txt contiene las ligas al mapa, las animaciones, el video y las comprobaciones. Necesitas internet para consultarlas; puedes trabajar en Compás sin conexión.</p>' +
    "<h3>3. Empieza con algo pequeño</h3><p>La primera vez verás un ejemplo ficticio. Puedes explorarlo o pulsar <strong>Empezar mi bitácora</strong>. Tu título y tu pregunta pueden quedar para después. Anota un paso pequeño en ToDo o escribe una página de tu Diario. <strong>No necesitas llenar todos los apartados.</strong></p>" +
    "<h3>4. Al terminar, guarda un respaldo y cierra la pestaña</h3><p>Pulsa <strong>Descargar respaldo</strong>. Localiza el archivo <strong>Compas-respaldo-personal-…json</strong> en tus descargas o en la carpeta que elegiste y pulsa <strong>Ya guardé el archivo</strong>. Puedes conservar el JSON en tu computadora o moverlo a una carpeta de Google Drive, OneDrive, Dropbox u otro servicio que ya uses. Necesitas internet para que ese servicio lo suba a la nube; comprueba que terminó de hacerlo. Compás no conecta cuentas ni sincroniza dispositivos. Después cierra la pestaña o la ventana del navegador. Compás no necesita quedarse abierto.</p>" +
    '<h3>5. La próxima vez, abre el mismo Compas.html</h3><p>Vuelve a la carpeta Compas y abre <strong>Compas.html</strong> con el mismo navegador. Puedes guardar un marcador o favorito para encontrarlo fácilmente. Que la dirección empiece con «file:» o que el navegador lo identifique como un archivo local es normal: esa es tu aplicación. La aplicación intentará retomar la copia que conservó allí. Si ves el ejemplo, faltan anotaciones o cambiaste de navegador o computadora, pulsa <strong>Abrir respaldo</strong> y elige tu JSON más reciente. Puedes trabajar sin internet después de descargar el paquete.</p><p class="hint">La aplicación es Compas.html. Tu trabajo se conserva en el respaldo JSON: guarda ambos en carpetas que puedas localizar.</p>' +
    '<details class="help-more"><summary>Guardado automático y respaldo</summary><p>Al pulsar <strong>Guardar cambios</strong> o marcar una tarea, el cambio se conserva automáticamente si la barra dice <strong>Guardado en este navegador</strong>. Lo que sólo has escrito dentro de un formulario aún abierto no se guarda hasta confirmar.</p><p><strong>Descargar respaldo</strong> crea una copia JSON para recuperar tu trabajo. No hace falta descargar para que funcione el guardado del navegador. Al abrir el mismo Compas.html con el mismo navegador y perfil, se recuperan tus anotaciones; normalmente vuelves a Brújula. Los formularios abiertos, filtros y desplazamiento no se conservan.</p><p>Si Compás dice <strong>Cambios solo en esta sesión</strong> o <strong>modo temporal</strong>, descarga un respaldo antes de cerrar. Borrar datos del navegador o usar navegación privada puede eliminar su copia auxiliar.</p></details>' +
    '<details class="help-more"><summary>Qué puedes hacer dentro de Compás</summary><ol class="help-list"><li><strong>Brújula y ToDo.</strong> Elige un paso posible y vuelve a tu tesis. Las tareas son privadas. Debajo de ellas puedes desplegar <strong>Registrar dedicación (opcional)</strong> para anotar actividades y horas; los registros anteriores siguen allí.</li><li><strong>Diario.</strong> Escribe una idea, una dificultad o cómo te fue hoy. Las reflexiones anteriores siguen aquí. No hay que escribir todos los días.</li><li><strong>Mi ruta.</strong> Consulta productos por semestre, registra versiones y adapta tu plan. Es una referencia en borrador, no una evaluación automática.</li><li><strong>Coloquios y Asesoría de tesis.</strong> Conserva conversaciones, acuerdos y decisiones para retomarlos cuando lo necesites.</li><li><strong>Reportes.</strong> Selecciona qué avances compartir y revisa la copia antes de descargar HTML, Excel o guardar PDF.</li></ol></details>' +
    '<details class="help-more"><summary>Llevar tus tareas a Google, Apple u Outlook</summary><p>En ToDo, pulsa <strong>Exportar a calendario</strong>, elige tareas pendientes con fecha y descarga el archivo ICS. Cada una aparecerá como un evento de día completo en su fecha prevista, sin hora.</p><p>En Google Calendar desde la computadora: <strong>Configuración → Importar y exportar</strong>. En Calendario de Apple en Mac: <strong>Archivo → Importar</strong>. En Outlook web: <strong>Agregar calendario → Cargar desde archivo</strong>. Elige el ICS y el calendario de destino.</p><p>Solo se incluyen títulos y fechas. Tus notas privadas y tu diario quedan fuera. Es una copia puntual: los cambios posteriores no se sincronizan y repetir la importación puede crear duplicados.</p></details>' +
    '<details class="help-more"><summary>Tu rincón: foto, marcos y detalles para acompañarte</summary><p>En Personalizar puedes elegir Aire, Cielo, Noche o IBERO y preparar tu rincón con una foto. Puedes elegir «Sin marco» o acompañarla con Lino, Madera, Jardín o Arcilla. Flores, hojas o estrellas se apoyan sobre las esquinas y los bordes; el centro de la foto queda despejado. La vista previa muestra cómo quedan juntos.</p><p>Sin foto, o si la usas como fondo suave, los adornos acompañan una tarjeta «A tu ritmo». Todos los marcos y adornos están disponibles desde el principio, también en los días difíciles.</p><p>Al terminar una tarea, producto o compromiso aparece una invitación discreta para elegir alguno de esos mismos detalles. Puedes cerrarla o desactivarla en Personalizar. No se desbloquean adornos nuevos ni se otorga una calificación o aprobación académica.</p><p>La foto, los marcos y los adornos permanecen en este navegador y quedan fuera de respaldos y reportes. Puedes volver a elegirlos al cambiar de equipo.</p></details>' +
    '<details class="help-more"><summary>Dónde vive tu bitácora: computadora y respaldo opcional en nube</summary><p>Trabaja en una computadora y con el mismo navegador: ahí se conserva la copia auxiliar. El respaldo JSON guarda tu trabajo completo. Si prefieres no usar nube, consérvalo en una carpeta de tu computadora y trabaja sin internet.</p><p>Si quieres una copia en nube, elige una carpeta de un servicio que ya tengas configurado o sube allí el JSON desde su página. La subida requiere internet. Guardar el respaldo en nube no mantiene abiertas otras copias ni transmite cambios automáticamente: esta versión se usa en computadora.</p><p>Al cambiar de computadora o navegador, descarga primero el respaldo más reciente, cierra la copia anterior y ábrelo en el nuevo lugar. Evita editar dos copias independientes.</p></details>' +
    '<details class="help-more"><summary>Respaldo, recuperación y actualización</summary><p>El respaldo JSON conserva tu bitácora completa, incluido el diario. La copia del navegador puede desaparecer al borrar sus datos o usar navegación privada. Por eso, guarda tu respaldo al terminar cada sesión.</p><p>Antes de abrir otro respaldo, conserva los cambios que quieras guardar. En Recuperación puedes descargar o retomar las copias anteriores disponibles. Una copia dañada puede descargarse para intentar recuperarla.</p><p>Para actualizar, descarga un respaldo desde la versión actual y cierra sus pestañas. Descomprime la versión nueva, abre su Compas.html y usa Abrir respaldo para retomar tus avances.</p><p>Usa una sola pestaña de edición. Otra pestaña queda en consulta y permite volver a comprobar después de cerrar la primera. Si el navegador no admite esa protección, se trabaja en modo temporal: descarga y confirma el respaldo antes de cerrar.</p></details>' +
    '<details class="help-more"><summary>Privacidad y qué se comparte</summary><p>Compás funciona sin internet y no envía tus anotaciones a servidores. No utiliza analítica ni servicios de inteligencia artificial.</p><p>Las tareas, horas, entradas del diario y notas privadas quedan fuera de los reportes. El respaldo personal sí las contiene y no está cifrado. Comparte el reporte seleccionado; conserva tu JSON contigo.</p><p>Registra decisiones y referencias de avance. Conserva entrevistas, transcripciones y bases de datos fuera de Compás. Si guardas el respaldo en una carpeta sincronizada, también puede almacenarse en la nube.</p><p>El reporte es una copia con fecha de corte. La revisión registrada por el tesista no equivale a una firma ni un VoBo verificado.</p></details>' +
    '<section class="support-contact"><h3>Fallas y comentarios</h3><p><a href="mailto:teresa.marquez@ibero.mx">teresa.marquez@ibero.mx</a></p><p><a href="https://github.com/tmarquez-mx/Compas" target="_blank" rel="noopener noreferrer">Descargas y repositorio de Compás</a></p><p class="hint">Describe qué ocurrió y qué navegador usas. Revisa que las capturas no muestren anotaciones privadas.</p></section><div class="toolbar">' +
    btn("Nueva bitácora", "new") +
    btn("Cargar ejemplo ficticio", "demo") +
    '</div><p class="keyboard-note">Los botones tienen explicaciones al pasar el ratón o enfocarlos con el teclado. Los campos con * son necesarios.</p></div><div class="dialog-bottom"><span class="hint">CSP | Universidad Iberoamericana Ciudad de México</span>' +
    btn("Entendido", "close", "", "primary") +
    "</div>";
  d.showModal();
}
